project:
  type: website
  output-dir: docs 
  render:
    - slides/01_intro.qmd
    - slides/02_graphs.qmd
    - slides/03_exper.qmd
    - slides/04_ob_conf.qmd
    - slides/05_dml.qmd
execute:
  freeze: auto  # re-render only when source changes
  
format-resources:
  - assets/author_pic.jpg